#!/usr/bin/env python3
"""Exact finite-state analyzer for one opposite-divisor gate.

For an odd modulus d and an integer x coprime to d, factor x as

    x = product q_i ** e_i.

A pair of coprime divisors a,b of x is obtained by assigning, for each prime
power q_i ** e_i, a positive exponent to at most one of a or b.  Therefore the
existence of d | a+b can be decided by a finite automaton on residue pairs
(a mod d, b mod d).  This script implements that exact criterion and can also
brute-force check it on supplied integers.

The program is a discovery and certificate-generation tool.  It is not a
universal proof of Erdős--Straus.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass, asdict
from pathlib import Path


@dataclass(frozen=True)
class Factor:
    prime: int
    exponent: int


def factorize(n: int) -> list[Factor]:
    if n < 1:
        raise ValueError("n must be positive")
    factors: list[Factor] = []
    p = 2
    remaining = n
    while p * p <= remaining:
        if remaining % p == 0:
            exponent = 0
            while remaining % p == 0:
                remaining //= p
                exponent += 1
            factors.append(Factor(p, exponent))
        p = 3 if p == 2 else p + 2
    if remaining > 1:
        factors.append(Factor(remaining, 1))
    return factors


def residue_pair_states(factors: list[Factor], modulus: int) -> set[tuple[int, int]]:
    """Return all pairs generated by disjoint prime-power assignments."""
    if modulus <= 1 or modulus % 2 == 0:
        raise ValueError("modulus must be an odd integer greater than one")
    states: set[tuple[int, int]] = {(1 % modulus, 1 % modulus)}
    for factor in factors:
        if math.gcd(factor.prime, modulus) != 1:
            raise ValueError("the exact unit-residue criterion requires gcd(x,d)=1")
        powers = {
            pow(factor.prime % modulus, exponent, modulus)
            for exponent in range(1, factor.exponent + 1)
        }
        next_states = set(states)
        for left, right in states:
            for power in powers:
                next_states.add(((left * power) % modulus, right))
                next_states.add((left, (right * power) % modulus))
        states = next_states
    return states


def automaton_witness(x: int, modulus: int) -> tuple[int, int] | None:
    factors = factorize(x)
    states: dict[tuple[int, int], tuple[int, int]] = {(1 % modulus, 1 % modulus): (1, 1)}
    for factor in factors:
        if math.gcd(factor.prime, modulus) != 1:
            raise ValueError("the exact unit-residue criterion requires gcd(x,d)=1")
        choices = [factor.prime**e for e in range(1, factor.exponent + 1)]
        next_states = dict(states)
        for residues, values in states.items():
            left_residue, right_residue = residues
            left_value, right_value = values
            for value in choices:
                next_states.setdefault(
                    ((left_residue * value) % modulus, right_residue),
                    (left_value * value, right_value),
                )
                next_states.setdefault(
                    (left_residue, (right_residue * value) % modulus),
                    (left_value, right_value * value),
                )
        states = next_states
    for (left_residue, right_residue), (left, right) in states.items():
        if (left_residue + right_residue) % modulus == 0:
            a, b = sorted((left, right))
            if a != b and math.gcd(a, b) == 1 and x % a == 0 and x % b == 0:
                return a, b
    return None


def brute_force_witness(x: int, modulus: int) -> tuple[int, int] | None:
    divisors = [d for d in range(1, math.isqrt(x) + 1) if x % d == 0]
    divisors = sorted(set(divisors + [x // d for d in divisors]))
    for i, a in enumerate(divisors):
        for b in divisors[i + 1 :]:
            if math.gcd(a, b) == 1 and (a + b) % modulus == 0:
                return a, b
    return None


def analyze(x: int, modulus: int) -> dict[str, object]:
    if math.gcd(x, modulus) != 1:
        raise ValueError("x and modulus must be coprime")
    factors = factorize(x)
    automaton = automaton_witness(x, modulus)
    brute = brute_force_witness(x, modulus)
    if (automaton is None) != (brute is None):
        raise AssertionError("automaton and brute-force criteria disagree")
    states = residue_pair_states(factors, modulus)
    return {
        "scope": "exact criterion for one finite x and one fixed odd modulus",
        "x": x,
        "modulus": modulus,
        "factorization": [asdict(factor) for factor in factors],
        "state_count": len(states),
        "has_opposite_coprime_divisors": automaton is not None,
        "automaton_witness": automaton,
        "brute_force_witness": brute,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("x", type=int)
    parser.add_argument("modulus", type=int)
    parser.add_argument("--json", type=Path)
    args = parser.parse_args()
    result = analyze(args.x, args.modulus)
    text = json.dumps(result, indent=2, sort_keys=True)
    print(text)
    if args.json:
        args.json.parent.mkdir(parents=True, exist_ok=True)
        args.json.write_text(text + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
